### ISSUE TITLE
Losing items after changing items per page

### ISSUE THREAD

**Issue by bositman** [luis-almeida/jPages#1]
The issue can be replicated even on the project's demo page here: 
http://luis-almeida.github.com/jPages/itemsperpage.html

If you change items per page a couple of times (and change the viewing page some times too) you will start to permanently lose some list items which never get visible again. 

My guess is that the new function to ignore hidden items on the item count is causing this, so when you have changed to eg page 2/20 then change items per page to something else, the moment jpages re-initializes the items of page 1 are hidden, thus are not counted toward the total.

Thanks for the great plugin btw :)

**Comment by luis-almeida** [comment]
The problem was in the destroy method that wasn't cleaning all the item's classes added by jPages.  
This wasn't an issue in the first release but since v0.2, pagination is only applied to visible items in order to make it possible to integrate with [filtrify](http://luis-almeida.github.com/filtrify/jpages.html).  
The items that were still hidden after "destroying" jPages weren't being counted anymore.

Thanks a lot for spotting this!!!
I just committed a few changes to fix this issue. Let me know if it's all well :)

**Comment by bositman** [comment]
Wow that was fast, works just fine thanks :)
While I'm at it, I have a question/suggestion: I'm using your plugin with a table which has a thead and a tfooter. The problem is that my structure is like this:
< table >
< thead >
< tfooter >
< tbody >
< tbody >
...
< /table >
Thus I can't use the trick you did in your table example, setting the ID of the tbody as the container to prevent it from counting thead and tfooter. Is there a possibility you could add an option to not count elements by ID? If not, maybe tell me a workaround to apply it in my case?
Thanks again :)

**Comment by luis-almeida** [comment]
Ya, that was a big issue so it had to be solved asap :)  

I'm not really understanding why can't you set an ID in the tbody. Is that because you have multiple tbodys in the table?

But anyway, there is a workaround you can do:
In the plugin constructor function you will find this line of code (line 60):

this._items = this._container.children(":visible");

All the items are being cached there and you can see we're only selecting all the visible children from the container.
You can edit this code to select only the items you want. For instance, you can add the container ID to the table tag and then edit that line to:

this._items = this._container.find("tbody tr:visible");

This will only select visible rows from the tbody.

Hope this helped :)
If not, make a jsFiddle and put your html there so I can have a better idea of what is the problem.

**Comment by bositman** [comment]
Indeed my problem was that I have multiple tbodys. Your workaround did the trick (although tbody tr:visible didn't find anything, I did it with tbody:visible)

Thanks for all the help and keep it up! I guess this issue can be closed now :)
