### ISSUE TITLE
Scroll only in one direction

### ISSUE THREAD

**Issue by me7hos** [luis-almeida/jPages#6]
Hi Luis,
first I want to thank you for the great plugins. You've done a really good job!

I'm testing the jPage plugin and i've one issue.

Look at this: http://extensions.styleware.eu/index.php/k2-jpage/k2-jpage-scroll-browse
The pages are scrolling only in one directions,regardless of which direction I move the mouse wheel.

Can you give me some hint what I miss?

**Comment by luis-almeida** [comment]
Hi @me7hos,

Thanks for pointing it out!
It turns out that in jQuery 1.7+, the detail property is not available at the jQuery event object.
I just committed a few changes to fix this bug and make this feature compatible with jQuery 1.7 and newer.

Get the last version of the plugin, try it and let me know if you still have any problems.

Cheers

**Comment by me7hos** [comment]
Hi Luis,
It works now.

Thank you!

Best Regards,
Mihail Semerdzhiev
